/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as HowToPlayRouteImport } from './routes/how-to-play'
import { Route as DailyRouteImport } from './routes/daily'
import { Route as AchievementsRouteImport } from './routes/achievements'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlayPuzzleIdRouteImport } from './routes/play.$puzzleId'

const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const HowToPlayRoute = HowToPlayRouteImport.update({
  id: '/how-to-play',
  path: '/how-to-play',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyRoute = DailyRouteImport.update({
  id: '/daily',
  path: '/daily',
  getParentRoute: () => rootRouteImport,
} as any)
const AchievementsRoute = AchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayPuzzleIdRoute = PlayPuzzleIdRouteImport.update({
  id: '/play/$puzzleId',
  path: '/play/$puzzleId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/achievements': typeof AchievementsRoute
  '/daily': typeof DailyRoute
  '/how-to-play': typeof HowToPlayRoute
  '/library': typeof LibraryRoute
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/play/$puzzleId': typeof PlayPuzzleIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/achievements': typeof AchievementsRoute
  '/daily': typeof DailyRoute
  '/how-to-play': typeof HowToPlayRoute
  '/library': typeof LibraryRoute
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/play/$puzzleId': typeof PlayPuzzleIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/achievements': typeof AchievementsRoute
  '/daily': typeof DailyRoute
  '/how-to-play': typeof HowToPlayRoute
  '/library': typeof LibraryRoute
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/play/$puzzleId': typeof PlayPuzzleIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/achievements'
    | '/daily'
    | '/how-to-play'
    | '/library'
    | '/settings'
    | '/stats'
    | '/play/$puzzleId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/achievements'
    | '/daily'
    | '/how-to-play'
    | '/library'
    | '/settings'
    | '/stats'
    | '/play/$puzzleId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/achievements'
    | '/daily'
    | '/how-to-play'
    | '/library'
    | '/settings'
    | '/stats'
    | '/play/$puzzleId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AchievementsRoute: typeof AchievementsRoute
  DailyRoute: typeof DailyRoute
  HowToPlayRoute: typeof HowToPlayRoute
  LibraryRoute: typeof LibraryRoute
  SettingsRoute: typeof SettingsRoute
  StatsRoute: typeof StatsRoute
  PlayPuzzleIdRoute: typeof PlayPuzzleIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-to-play': {
      id: '/how-to-play'
      path: '/how-to-play'
      fullPath: '/how-to-play'
      preLoaderRoute: typeof HowToPlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily': {
      id: '/daily'
      path: '/daily'
      fullPath: '/daily'
      preLoaderRoute: typeof DailyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achievements': {
      id: '/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/$puzzleId': {
      id: '/play/$puzzleId'
      path: '/play/$puzzleId'
      fullPath: '/play/$puzzleId'
      preLoaderRoute: typeof PlayPuzzleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AchievementsRoute: AchievementsRoute,
  DailyRoute: DailyRoute,
  HowToPlayRoute: HowToPlayRoute,
  LibraryRoute: LibraryRoute,
  SettingsRoute: SettingsRoute,
  StatsRoute: StatsRoute,
  PlayPuzzleIdRoute: PlayPuzzleIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
